application_tracker/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from application_tracker.views import authentication, dashboard, platform, application_status, application, application_history
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'application_tracker'

config_platform_url = [
    path('', platform.GetAll.as_view(), name="list_platform"),
    path('/new', platform.Create.as_view(), name="create_platform"),
    path('/<id>/edit', platform.Edit.as_view(), name="edit_platform"),
    path('/<id>/delete', platform.Delete.as_view(), name="delete_platform"),
]

config_application_status_url = [
    path('', application_status.GetAll.as_view(), name="list_application_status"),
    path('/new', application_status.Create.as_view(), name="create_application_status"),
    path('/<id>/edit', application_status.Edit.as_view(), name="edit_application_status"),
    path('/<id>/delete', application_status.Delete.as_view(), name="delete_application_status"),
]

config_url = [
    path("/platform", include(config_platform_url)),
    path("/application-status", include(config_application_status_url)),
]

application_history_url = [
    path('/history/<id>', application_history.Delete.as_view(), name="delete_application_history"),
    path('/history', application_history.Create.as_view(), name="create_application_history"),
]

application_url = [
    path('', application.GetAll.as_view(), name="list_application"),
    path('/new', application.Create.as_view(), name="create_application"),
    path('/<id>/delete', application.Delete.as_view(), name="delete_application"),
    path('/<id>/edit', application.Edit.as_view(), name="edit_application"),
    path('/<id>', application.Detail.as_view(), name="detail_application"),
    path('/<application_id>', include(application_history_url)),
]

urlpatterns = [
    path('login', authentication.Login.as_view(), name="login"),
    path('register', authentication.Register.as_view(), name="register"),
    path('logout', authentication.Logout.as_view(), name="logout"),
    path('', dashboard.Home.as_view(), name='home'),
    path('config', include(config_url)),
    path('application', include(application_url))
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from application_tracker import views
from django.conf.urls.static import static
from django.conf import settings

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include("application_tracker.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

application_tracker/views.py
from django.shortcuts import render, redirect
from .models import User, Application, ApplicationHistory
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from . import forms
from application_tracker.common.errors import getErrorMessageFromForm
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url='application_tracker:login')
def Home(request):
    return render(request, 'home.html')


def LoginPage(request):
    context = {}
    if request.user.is_authenticated:
        return redirect('application_tracker:home')

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('application_tracker:home')
        else:
            messages.error(request, "Username or password invalid")
            return HttpResponseRedirect("/login")

    return render(request, 'authentication/login.html', context)


def RegisterPage(request):
    context = {}
    if request.method == "POST":
        form = forms.NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("application_tracker:home")
        else:
            context['form'] = form
            messages.error(request, getErrorMessageFromForm(form))

            return HttpResponseRedirect("/register")

    else:
        form = forms.NewUserForm()
        context['form'] = form

    return render(request, "authentication/register.html", context)


def Logout(request):
    logout(request)
    return redirect("application_tracker:login")

application_tracker/views/application.py
from application_tracker.models import Application, Platform, ApplicationStatus, ApplicationHistory
from application_tracker.common.pagination import GetPaginationRequest
from application_tracker.forms import CreateApplicationForm, UpdateApplicationForm
from application_tracker.common.errors import getErrorMessageFromForm

from django.core.paginator import Paginator
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db import DatabaseError, transaction
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import View
from django.utils.decorators import method_decorator
import datetime

canceled_redirect_url_key = "canceled_redirect_url"
create_url_key = "create_url"

base_url = "/application"
url_list = base_url
create_url = f"{base_url}/new"

base_template_path = "page/application/"

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class GetAll(View):
    context = {
        create_url_key:create_url
    }
    template = base_template_path + "list.html"

    def get(self, request):
        pagination_request = GetPaginationRequest()

        # Get sort field and direction from query parameters
        sort_field = request.GET.get("sort", "")  # Default sorting field
        sort_direction = request.GET.get("direction", "")  # Default sorting direction

        # Validate direction and prepare ordering string
        if sort_direction == "desc":
            order_by = f"-{sort_field}"
        else:
            order_by = sort_field
        
        # Reset to default if no sorting parameters are provided
        if not request.GET.get("sort") and not request.GET.get("direction"):
            order_by = "-created_at"  # Default order by ID ascending
        
        application_status = Application.objects.all()
        application_status = application_status.filter(user=request.user.id).order_by(order_by)

        paginator = Paginator(application_status, pagination_request.get_per_page(request))
            
        data = paginator.get_page(pagination_request.get_page(request))

        self.context["pagination_data"] = data
        self.context["is_application"] = "active"
        self.context["current_sort"] = sort_field
        self.context["current_direction"] = sort_direction

        return render(request, self.template, self.context)

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Create(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "create.html"
    path = create_url

    def get(self, request):
        platform = Platform.objects.filter(user=request.user).order_by("name")
        self.context['platform'] = platform

        form = CreateApplicationForm(request.GET)
        self.context['form'] = form

        application_status = ApplicationStatus.objects.filter(user=request.user).order_by("name")
        self.context['application_status'] = application_status
        return render(request, self.template, self.context)

    def post(self, request):
        form = CreateApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.user = request.user
            try:
                with transaction.atomic():
                    application.save()

                    application_history = ApplicationHistory()
                    application_history.status = application.last_status
                    application_history.application = application
                    application_history.update_status_at = application.last_updated
                    application_history.note = request.POST.get("note")
                    application_history.save()
            except DatabaseError as e:
                msg = ValidationError(e).messages[0]
                messages.error(request, msg)
                return HttpResponseRedirect(self.path)

            except:
                messages.error(request, "Error server")
                return HttpResponseRedirect(self.path)

            return HttpResponseRedirect(url_list)
        else:
            self.context['form'] = form
            messages.error(request, getErrorMessageFromForm(form))
            return HttpResponseRedirect(self.path)

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Delete(View):
    context = {}
    template = base_template_path + "list.html"
    path = base_url

    def get(self, request, id):
        try:
            with transaction.atomic():
                ApplicationHistory.objects.filter(application_id=id).delete()
                Application.objects.filter(id=id, user=request.user).delete()
        except:
            messages.error(request, f"Failed to delete application with id {id}")
        return HttpResponseRedirect(self.path)

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Edit(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "edit.html"
    
    def insert_id_to_path(self, id):
        return f"{base_url}/{id}/edit"
    
    def get_detail_data(self, id, user):
        return Application.objects.get(id=id, user=user)

    def get(self, request, id):
        try:
            data = self.get_detail_data(id, request.user)
            self.context['data'] = data

            platform = Platform.objects.filter(user=request.user).order_by("name")
            self.context['platform'] = platform
        except:
            self.template = "page/data_not_found.html"
        return render(request, self.template, self.context)

    def post(self, request, id):
        current_data = self.get_detail_data(id, request.user)
        form = UpdateApplicationForm(request.POST, instance=current_data)
        if form.is_valid():
            try:
                post = form.save(commit=False)
                post.updated_at = datetime.datetime.now()
                post.save()
            except:
                messages.error(request, "Error server")
                return HttpResponseRedirect(self.insert_id_to_path(id))

            return HttpResponseRedirect(base_url)

        self.context['form'] = form
        messages.error(request, getErrorMessageFromForm(form))
        return HttpResponseRedirect(self.insert_id_to_path(id))

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Detail(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "detail.html"

    def get_detail_data(self, id, user):
        return Application.objects.get(id=id, user=user)

    def get(self, request, id):
        try:
            data = self.get_detail_data(id, request.user)
            self.context['data'] = data

            histories = ApplicationHistory.objects.filter(application_id=data.id).order_by("-update_status_at", "-created_at")
            self.context['histories'] = histories
        except:
            self.template = "page/data_not_found.html"
        return render(request, self.template, self.context)

application_tracker/views/application_history.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db import DatabaseError, transaction
from django.core.exceptions import ValidationError

from application_tracker.models import ApplicationHistory, Application, ApplicationStatus
from application_tracker.forms import CreateNewApplicationHistoryForm
from application_tracker.common.errors import getErrorMessageFromForm

canceled_redirect_url_key = "canceled_redirect_url"

base_template_path = "page/application_history/"
base_url = "/application"
url_list = base_url

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Delete(View):
    context = {}
    template = base_template_path + "detail.html"
    path = base_url

    def get(self, request, application_id, id):
        try:
            with transaction.atomic():
                ApplicationHistory.objects.filter(application_id=application_id, id=id).delete()

                # get last history
                history = ApplicationHistory.objects.filter(application_id=application_id).order_by("-update_status_at", "-created_at")[0]

                application = Application.objects.get(id=application_id)
                application.last_status = history.status
                application.last_updated = history.update_status_at
                application.save()
        except:
            messages.error(request, f"Failed to delete application with id {id}")
        return HttpResponseRedirect(self.path + f"/{application_id}")

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Create(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "create.html"
    path = base_url

    def get(self, request, application_id):
        self.context[canceled_redirect_url_key] = url_list + f"/{application_id}"
        
        form = CreateNewApplicationHistoryForm(request.GET)
        self.context['form'] = form

        application = Application.objects.get(user=request.user, id=application_id)
        self.context['application'] = application

        application_status = ApplicationStatus.objects.filter(user=request.user).order_by("name")
        self.context['application_status'] = application_status
        return render(request, self.template, self.context)

    def post(self, request, application_id):
        history_path = self.path + f"/{application_id}/history"
        detail_path = self.path + f"/{application_id}"
        
        form = CreateNewApplicationHistoryForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user

            application = Application.objects.get(id=application_id)
            post.application = application
            try:
                with transaction.atomic():
                    post.save()

                    # get last history
                    history = ApplicationHistory.objects.filter(application_id=application_id).order_by("-update_status_at", "-created_at")[0]

                    application.last_status = history.status
                    application.last_updated = history.update_status_at
                    application.save()
            except DatabaseError as e:
                msg = ValidationError(e).messages[0]
                messages.error(request, msg)
                return HttpResponseRedirect(history_path)

            except:
                messages.error(request, "Error server")
                return HttpResponseRedirect(history_path)

            return HttpResponseRedirect(detail_path)
        else:
            self.context['form'] = form
            messages.error(request, getErrorMessageFromForm(form))
            return HttpResponseRedirect(history_path)

application_tracker/views/dashboard.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import View
from django.utils.decorators import method_decorator

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Home(View):
    context = {
        "is_dashboard":"active",
    }
    def get(self, request):
        return render(request, 'page/home.html', self.context)

application_tracker/templates/config/platform/create.html
{% extends '../../component/form.html' %}

{% block title %}
<title>Create Config Platform</title>
{% endblock %}

{% block title_form_create %}
<h3 class="mb-4">Create Platform</h3>
{% endblock %}

{% block form_create %}
    <div class="row mb-3">
        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="name" class="form-control" id="inputName" name="name">
        </div>
    </div>
{% endblock %}

application_tracker/templates/config/platform/edit.html
{% extends '../../component/form.html' %}

{% block title %}
<title>Edit Config Platform</title>
{% endblock %}

{% block title_form_create %}
<h3 class="mb-4">Edit Platform</h3>
{% endblock %}

{% block form_create %}
    <div class="row mb-3">
        <label for="inputName" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="name" class="form-control" id="inputName" name="name" value="{{data.name}}">
        </div>
    </div>
{% endblock %}

application_tracker/templates/config/platform/list.html
{% extends '../../component/list_table.html' %}

{% block title %}
<title>Config Platform</title>
{% endblock %}

{% block table_title %}
<h3 class="m-2">Platforms</h3>
{% endblock %}

{% block table_header %}
<tr>
    <th scope="col">No</th>
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Created At</th>
    <th scope="col">Actions</th>
</tr>
{% endblock %}

{% block table_data %}
    {% for item in pagination_data %}
    <tr>
        <th scope="row">{{pagination_data.start_index|add:forloop.counter0}}</th>
        <th>{{item.id}}</th>
        <td>{{item.name}}</td>
        <td>{{item.created_at}}</td>
        <td>
            <a href="{% url 'application_tracker:edit_platform' item.id %}" class="me-4">
                <i class="fa fa-pencil-alt"></i>
            </a>
            <a href="{% url 'application_tracker:delete_platform' item.id %}">
                <i class="fa fa-eraser"></i>
            </a>
        </td>
    </tr>
    {% endfor %}
{% endblock %}

application_tracker/templates/config/platform/platform.html
{% extends '../../base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
<title>Config Platform</title>
{% endblock %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Platforms</h6>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Created At</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in pagination_data %}
                            <tr>
                                <th scope="row">{{pagination_data.start_index|add:forloop.counter0}}</th>
                                <th>{{item.id}}</th>
                                <td>{{item.name}}</td>
                                <td>{{item.created_at}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- <form action="{% url 'application_tracker:platform' %}" method="get">
                    <select class="form-select form-select-sm mb-3" aria-label=".form-select-sm example" name="limit">
                        <option value="5" selected>5</option>
                        <option value="10">10</option>
                        <option value="50">50</option>
                    </select>
                </form> -->


                <!-- PAGINATION -->
                {% include '../../component/pagination.html' %}
            </div>
        </div>
    </div>
</div>

{% endblock %}