application_tracker/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from application_tracker.views import authentication, dashboard, platform, application_status, application, application_history
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'application_tracker'

config_platform_url = [
    path('', platform.GetAll.as_view(), name="list_platform"),
    path('/new', platform.Create.as_view(), name="create_platform"),
    path('/<id>/edit', platform.Edit.as_view(), name="edit_platform"),
    path('/<id>/delete', platform.Delete.as_view(), name="delete_platform"),
]

config_application_status_url = [
    path('', application_status.GetAll.as_view(), name="list_application_status"),
    path('/new', application_status.Create.as_view(), name="create_application_status"),
    path('/<id>/edit', application_status.Edit.as_view(), name="edit_application_status"),
    path('/<id>/delete', application_status.Delete.as_view(), name="delete_application_status"),
]

config_url = [
    path("/platform", include(config_platform_url)),
    path("/application-status", include(config_application_status_url)),
]

application_history_url = [
    path('/history/<id>', application_history.Delete.as_view(), name="delete_application_history"),
    path('/history', application_history.Create.as_view(), name="create_application_history"),
]

application_url = [
    path('', application.GetAll.as_view(), name="list_application"),
    path('/new', application.Create.as_view(), name="create_application"),
    path('/<id>/delete', application.Delete.as_view(), name="delete_application"),
    path('/<id>/edit', application.Edit.as_view(), name="edit_application"),
    path('/<id>', application.Detail.as_view(), name="detail_application"),
    path('/<application_id>', include(application_history_url)),
]

urlpatterns = [
    path('login', authentication.Login.as_view(), name="login"),
    path('register', authentication.Register.as_view(), name="register"),
    path('logout', authentication.Logout.as_view(), name="logout"),
    path('', dashboard.Home.as_view(), name='home'),
    path('config', include(config_url)),
    path('application', include(application_url))
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from application_tracker import views
from django.conf.urls.static import static
from django.conf import settings

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include("application_tracker.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

application_tracker/views.py
from django.shortcuts import render, redirect
from .models import User, Application, ApplicationHistory
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from . import forms
from application_tracker.common.errors import getErrorMessageFromForm
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url='application_tracker:login')
def Home(request):
    return render(request, 'home.html')


def LoginPage(request):
    context = {}
    if request.user.is_authenticated:
        return redirect('application_tracker:home')

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('application_tracker:home')
        else:
            messages.error(request, "Username or password invalid")
            return HttpResponseRedirect("/login")

    return render(request, 'authentication/login.html', context)


def RegisterPage(request):
    context = {}
    if request.method == "POST":
        form = forms.NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("application_tracker:home")
        else:
            context['form'] = form
            messages.error(request, getErrorMessageFromForm(form))

            return HttpResponseRedirect("/register")

    else:
        form = forms.NewUserForm()
        context['form'] = form

    return render(request, "authentication/register.html", context)


def Logout(request):
    logout(request)
    return redirect("application_tracker:login")

application_tracker/views/application.py
from application_tracker.models import Application, Platform, ApplicationStatus, ApplicationHistory
from application_tracker.common.pagination import GetPaginationRequest
from application_tracker.forms import CreateApplicationForm, UpdateApplicationForm
from application_tracker.common.errors import getErrorMessageFromForm

from django.core.paginator import Paginator
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db import DatabaseError, transaction
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import View
from django.utils.decorators import method_decorator
import datetime

canceled_redirect_url_key = "canceled_redirect_url"
create_url_key = "create_url"

base_url = "/application"
url_list = base_url
create_url = f"{base_url}/new"

base_template_path = "page/application/"

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class GetAll(View):
    context = {
        create_url_key:create_url
    }
    template = base_template_path + "list.html"

    def get(self, request):
        pagination_request = GetPaginationRequest()

        # Get sort field and direction from query parameters
        sort_field = request.GET.get("sort", "")  # Default sorting field
        sort_direction = request.GET.get("direction", "")  # Default sorting direction

        # Validate direction and prepare ordering string
        if sort_direction == "desc":
            order_by = f"-{sort_field}"
        else:
            order_by = sort_field
        
        # Reset to default if no sorting parameters are provided
        if not request.GET.get("sort") and not request.GET.get("direction"):
            order_by = "-created_at"  # Default order by ID ascending
        
        application_status = Application.objects.all()
        application_status = application_status.filter(user=request.user.id).order_by(order_by)

        paginator = Paginator(application_status, pagination_request.get_per_page(request))
            
        data = paginator.get_page(pagination_request.get_page(request))

        self.context["pagination_data"] = data
        self.context["is_application"] = "active"
        self.context["current_sort"] = sort_field
        self.context["current_direction"] = sort_direction

        return render(request, self.template, self.context)

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Create(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "create.html"
    path = create_url

    def get(self, request):
        platform = Platform.objects.filter(user=request.user).order_by("name")
        self.context['platform'] = platform

        form = CreateApplicationForm(request.GET)
        self.context['form'] = form

        application_status = ApplicationStatus.objects.filter(user=request.user).order_by("name")
        self.context['application_status'] = application_status
        return render(request, self.template, self.context)

    def post(self, request):
        form = CreateApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.user = request.user
            try:
                with transaction.atomic():
                    application.save()

                    application_history = ApplicationHistory()
                    application_history.status = application.last_status
                    application_history.application = application
                    application_history.update_status_at = application.last_updated
                    application_history.note = request.POST.get("note")
                    application_history.save()
            except DatabaseError as e:
                msg = ValidationError(e).messages[0]
                messages.error(request, msg)
                return HttpResponseRedirect(self.path)

            except:
                messages.error(request, "Error server")
                return HttpResponseRedirect(self.path)

            return HttpResponseRedirect(url_list)
        else:
            self.context['form'] = form
            messages.error(request, getErrorMessageFromForm(form))
            return HttpResponseRedirect(self.path)

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Delete(View):
    context = {}
    template = base_template_path + "list.html"
    path = base_url

    def get(self, request, id):
        try:
            with transaction.atomic():
                ApplicationHistory.objects.filter(application_id=id).delete()
                Application.objects.filter(id=id, user=request.user).delete()
        except:
            messages.error(request, f"Failed to delete application with id {id}")
        return HttpResponseRedirect(self.path)

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Edit(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "edit.html"
    
    def insert_id_to_path(self, id):
        return f"{base_url}/{id}/edit"
    
    def get_detail_data(self, id, user):
        return Application.objects.get(id=id, user=user)

    def get(self, request, id):
        try:
            data = self.get_detail_data(id, request.user)
            self.context['data'] = data

            platform = Platform.objects.filter(user=request.user).order_by("name")
            self.context['platform'] = platform
        except:
            self.template = "page/data_not_found.html"
        return render(request, self.template, self.context)

    def post(self, request, id):
        current_data = self.get_detail_data(id, request.user)
        form = UpdateApplicationForm(request.POST, instance=current_data)
        if form.is_valid():
            try:
                post = form.save(commit=False)
                post.updated_at = datetime.datetime.now()
                post.save()
            except:
                messages.error(request, "Error server")
                return HttpResponseRedirect(self.insert_id_to_path(id))

            return HttpResponseRedirect(base_url)

        self.context['form'] = form
        messages.error(request, getErrorMessageFromForm(form))
        return HttpResponseRedirect(self.insert_id_to_path(id))

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Detail(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "detail.html"

    def get_detail_data(self, id, user):
        return Application.objects.get(id=id, user=user)

    def get(self, request, id):
        try:
            data = self.get_detail_data(id, request.user)
            self.context['data'] = data

            histories = ApplicationHistory.objects.filter(application_id=data.id).order_by("-update_status_at", "-created_at")
            self.context['histories'] = histories
        except:
            self.template = "page/data_not_found.html"
        return render(request, self.template, self.context)

application_tracker/views/application_history.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db import DatabaseError, transaction
from django.core.exceptions import ValidationError

from application_tracker.models import ApplicationHistory, Application, ApplicationStatus
from application_tracker.forms import CreateNewApplicationHistoryForm
from application_tracker.common.errors import getErrorMessageFromForm

canceled_redirect_url_key = "canceled_redirect_url"

base_template_path = "page/application_history/"
base_url = "/application"
url_list = base_url

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Delete(View):
    context = {}
    template = base_template_path + "detail.html"
    path = base_url

    def get(self, request, application_id, id):
        try:
            with transaction.atomic():
                ApplicationHistory.objects.filter(application_id=application_id, id=id).delete()

                # get last history
                history = ApplicationHistory.objects.filter(application_id=application_id).order_by("-update_status_at", "-created_at")[0]

                application = Application.objects.get(id=application_id)
                application.last_status = history.status
                application.last_updated = history.update_status_at
                application.save()
        except:
            messages.error(request, f"Failed to delete application with id {id}")
        return HttpResponseRedirect(self.path + f"/{application_id}")

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Create(View):
    context = {
        canceled_redirect_url_key:url_list
    }
    template = base_template_path + "create.html"
    path = base_url

    def get(self, request, application_id):
        self.context[canceled_redirect_url_key] = url_list + f"/{application_id}"
        
        form = CreateNewApplicationHistoryForm(request.GET)
        self.context['form'] = form

        application = Application.objects.get(user=request.user, id=application_id)
        self.context['application'] = application

        application_status = ApplicationStatus.objects.filter(user=request.user).order_by("name")
        self.context['application_status'] = application_status
        return render(request, self.template, self.context)

    def post(self, request, application_id):
        history_path = self.path + f"/{application_id}/history"
        detail_path = self.path + f"/{application_id}"
        
        form = CreateNewApplicationHistoryForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user

            application = Application.objects.get(id=application_id)
            post.application = application
            try:
                with transaction.atomic():
                    post.save()

                    # get last history
                    history = ApplicationHistory.objects.filter(application_id=application_id).order_by("-update_status_at", "-created_at")[0]

                    application.last_status = history.status
                    application.last_updated = history.update_status_at
                    application.save()
            except DatabaseError as e:
                msg = ValidationError(e).messages[0]
                messages.error(request, msg)
                return HttpResponseRedirect(history_path)

            except:
                messages.error(request, "Error server")
                return HttpResponseRedirect(history_path)

            return HttpResponseRedirect(detail_path)
        else:
            self.context['form'] = form
            messages.error(request, getErrorMessageFromForm(form))
            return HttpResponseRedirect(history_path)

application_tracker/views/dashboard.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import View
from django.utils.decorators import method_decorator

@method_decorator(login_required(login_url='application_tracker:login'), name='get')
class Home(View):
    context = {
        "is_dashboard":"active",
    }
    def get(self, request):
        return render(request, 'page/home.html', self.context)

application_tracker/templates/component/after_content.html
{% load static %}

    {% include 'component/footer.html' %}
</div>

{% include 'component/back_to_top.html' %}

application_tracker/templates/component/back_to_top.html
{% load static %}

<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>

application_tracker/templates/component/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    {% load humanize %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}
    {% endblock %}

    {% block style %}
    {% endblock %}

    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative bg-white d-flex p-0">
        {% include './spinner.html' %}

        {% if user.is_authenticated %}
        {% include './before_content.html' %}
        {% endif %}

        {% block content %}
        {% endblock %}

        {% if user.is_authenticated %}
        {% include './after_content.html' %}
        {% endif %}
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>

    {% block additional_script %}
    {% endblock %}
</body>

</html>

application_tracker/templates/component/before_content.html
{% load static %}

{% include 'component/sidebar.html' %}

    <div class="content">
        {% include 'component/navbar.html' %}

application_tracker/templates/component/detail.html
{% extends './base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <div style="display: flex; justify-content: space-between;">
                    {% block title_detail_data %}
                    {% endblock %}
                </div>

                {% block detail_data %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

application_tracker/templates/component/error_message.html
{% load static %}

{% for message in messages %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="fa fa-exclamation-circle me-2"></i>{{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

application_tracker/templates/component/footer.html
{% load static %}

<!-- Footer Start -->
<div class="container-fluid pt-4 px-4">
    <div class="bg-light rounded-top p-4">
        <div class="row">
            <div class="col-12 col-sm-6 text-center text-sm-start">
                &copy; <a href="{% url 'application_tracker:home' %}">Application Tracker</a>, All Right Reserved. 
            </div>
            <div class="col-12 col-sm-6 text-center text-sm-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By <a href="https://htmlcodex.com">HTML Codex</a>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

application_tracker/templates/component/form.html
{% extends './base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                {% block title_form_create %}
                {% endblock %}
                <form method="POST">
                    {% csrf_token %}

                    {% block form_create %}
                    {% endblock %}

                    {% include '../component/error_message.html' %}
                    <div>
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{{canceled_redirect_url}}">
                            <button type="button" class="btn btn-outline-primary">Cancel</button>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

application_tracker/templates/component/navbar.html
{% load static %}

<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
    <a href="{% url 'application_tracker:home' %}" class="navbar-brand d-flex d-lg-none me-4">
        <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
    </a>
    <a href="#" class="sidebar-toggler flex-shrink-0">
        <i class="fa fa-bars"></i>
    </a>
    <!-- <form class="d-none d-md-flex ms-4">
        <input class="form-control border-0" type="search" placeholder="Search">
    </form> -->
    <div class="navbar-nav align-items-center ms-auto">
        <!-- <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-envelope me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Message</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt=""
                            style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt=""
                            style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt=""
                            style="width: 40px; height: 40px;">
                        <div class="ms-2">
                            <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                            <small>15 minutes ago</small>
                        </div>
                    </div>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all message</a>
            </div>
        </div>
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-bell me-lg-2"></i>
                <span class="d-none d-lg-inline-flex">Notification</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Profile updated</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">New user added</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item">
                    <h6 class="fw-normal mb-0">Password changed</h6>
                    <small>15 minutes ago</small>
                </a>
                <hr class="dropdown-divider">
                <a href="#" class="dropdown-item text-center">See all notifications</a>
            </div>
        </div> -->
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <img class="rounded-circle me-lg-2" src="{% static 'img/user.jpg' %}" alt=""
                    style="width: 40px; height: 40px;">
                <span class="d-none d-lg-inline-flex">{{user.first_name}}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="#" class="dropdown-item">My Profile</a>
                <a href="#" class="dropdown-item">Settings</a>
                <a href="{% url 'application_tracker:logout'%}" class="dropdown-item">Log Out</a>
            </div>
        </div>
    </div>
</nav>
<!-- Navbar End -->

application_tracker/templates/component/sidebar.html
{% load static %}

<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a href="{% url 'application_tracker:home' %}" class="navbar-brand mx-4 mb-3">
            <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>DASHMIN</h3>
        </a>
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="{% static 'img/user.jpg' %}" alt="" style="width: 40px; height: 40px;">
                <div
                    class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                </div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{{user.first_name}}</h6>
                <!-- <span>Admin</span> -->
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'application_tracker:home' %}" class="nav-item nav-link {{is_dashboard}}">
                <i class="fa fa-tachometer-alt me-2"></i>Dashboard
            </a>
            <a href="{% url 'application_tracker:list_application' %}" class="nav-item nav-link {{is_application}}">
                <i class="fa fa-th me-2"></i>Application
            </a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle {{is_config}}" data-bs-toggle="dropdown"><i
                        class="fa fa-laptop me-2"></i>Config</a>
                <div class="dropdown-menu bg-transparent border-0">
                    <a href="{% url 'application_tracker:list_platform' %}"
                        class="dropdown-item {{is_platform}}">Platform</a>
                    <a href="{% url 'application_tracker:list_application_status' %}"
                        class="dropdown-item {{is_application_status}}">Application Status</a>
                    <!-- <a href="element.html" class="dropdown-item">Other Elements</a> -->
                </div>
            </div>
            <!-- <a href="form.html" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Forms</a>
            <a href="table.html" class="nav-item nav-link"><i class="fa fa-table me-2"></i>Tables</a>
            <a href="chart.html" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Charts</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                <div class="dropdown-menu bg-transparent border-0">
                    <a href="signin.html" class="dropdown-item">Sign In</a>
                    <a href="signup.html" class="dropdown-item">Sign Up</a>
                    <a href="404.html" class="dropdown-item">404 Error</a>
                    <a href="blank.html" class="dropdown-item">Blank Page</a>
                </div>
            </div> -->
        </div>
    </nav>
</div>
<!-- Sidebar End -->

application_tracker/templates/component/spinner.html
{% load static %}

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!-- Spinner End -->